version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://13.232.106.238/api
    image: lostvraj/invoizo-client:latest
    env_file:
      - ./client/.env
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "80:80"
    restart: always  
    depends_on:
      - server
    networks:
      - invoizo-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: lostvraj/invoizo-server:latest  
    environment:
      - MONGO_URI=mongodb+srv://vrajlk:vrajlk@myshop.v9upd.mongodb.net/Myshop?retryWrites=true&w=majority&appName=MyShop
      - JWT_SECRET=vrajlk
    ports:
      - "3000:3000"
    restart: always  
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - invoizo-network

  mongo:
    image: mongo:latest
    volumes:
      - invoizo-db:/data/db
    networks:
      - invoizo-network

networks:
  invoizo-network:
    driver: bridge

volumes:
  invoizo-db: